### ISSUE TITLE
Usage unclear

### ISSUE THREAD

**Issue by estahn** [artprima/prometheus-metrics-bundle#2]
We want to collect business metrics and I created a class `OrderMetrics` extending from `MetricsGeneratorInterface`. It's registered in `services.yaml`:

```
    App\Metrics\:
        resource: '../src/Metrics'
        tags: ['prometheus_metrics_bundle.metrics_generator']
```

However, it doesn't seem to do anything. What does `collectRequest` and `collectResponse` do? There is no documentation on these. Shouldn't there be a `collect` method only?

**Comment by denisvmedia** [comment]
Did you try doing that on a per-class basis? I.e. exactly like in the documentation:

```
    App\Metrics\MyMetricsGenerator:
        tags:
            - { name: prometheus_metrics_bundle.metrics_generator }
```

To get more details on `collectRequest` and `collectResponse` you can check this file: https://github.com/artprima/prometheus-metrics-bundle/blob/master/Metrics/AppMetrics.php

Basically, in the `init` function you get the namespace and the collectionRegistry, you should save them in to a private field, and then use in `collectRequest` (called on `kernel.request` event) and/or `collectResponse` (called on `kernel.terminate` event). You can check how they are called here: https://github.com/artprima/prometheus-metrics-bundle/blob/master/EventListener/RequestCounterListener.php .

And yes, you are right, the documentation is not good enough. I will add more details to it according to your question.

**Comment by denisvmedia** [comment]
I updated the doc: https://github.com/artprima/prometheus-metrics-bundle#custom-metrics-generator

**Comment by estahn** [comment]
@denisvmedia Thanks. It seems to me that the `MetricInterface` implements something specific that you need for calculating a specific metric. It's completely irrelevant for business metrics, e.g.

```
class OrderMetrics implements ... {
}
```

Why would I need to implement `collectRequest` and `collectResponse` in this case? I just want to provide the number of orders (`orders_total`).

**Comment by denisvmedia** [comment]
Well, what's wrong with collecting the metrics in `collectRequest`? And if you don't need `collectResponse`, you can just leave it empty.
