### ISSUE TITLE
apcu_store error Symfony 4.4

### ISSUE THREAD

**Issue by ValentinClementFr** [artprima/prometheus-metrics-bundle#24]
Hi,

I try to add your bundle to my symfony project but I have an error when I'm connecting to my first page :

Attempted to call function "apcu_store" from namespace "Prometheus\Storage".

(1/1) UndefinedFunctionExceptionAttempted to call function "apcu_store" from namespace "Prometheus\Storage".
--
in APC.php line 71
at APC->updateGauge(array('name' => 'php_info', 'help' => 'Information about the PHP environment.', 'type' => 'gauge', 'labelNames' => array('version'), 'labelValues' => array('7.2.25'), 'value' => 1.0, 'command' => 3))in Gauge.php line 23
at Gauge->set(1.0, array('7.2.25'))in CollectorRegistry.php line 286
at CollectorRegistry->registerDefaultMetrics()in CollectorRegistry.php line 54
at CollectorRegistry->__construct(object(APC))in srcApp_KernelDevDebugContainer.php line 1261
at srcApp_KernelDevDebugContainer->getPrometheusMetricsBundle_CollectorRegistryService()in srcApp_KernelDevDebugContainer.php line 433
at srcApp_KernelDevDebugContainer->getAppMetricsService()in srcApp_KernelDevDebugContainer.php line 447
at srcApp_KernelDevDebugContainer->getMetricsGeneratorRegistryService()in srcApp_KernelDevDebugContainer.php line 417
at srcApp_KernelDevDebugContainer->getRequestCounterListenerService()in srcApp_KernelDevDebugContainer.php line 515
at srcApp_KernelDevDebugContainer->ContainerQ5OIyCT\{closure}()in EventDispatcher.php line 279
at EventDispatcher->sortListeners('kernel.request')in EventDispatcher.php line 90
at EventDispatcher->getListeners('kernel.request')in TraceableEventDispatcher.php line 334
at TraceableEventDispatcher->preProcess('kernel.request')in TraceableEventDispatcher.php line 162
at TraceableEventDispatcher->dispatch(object(RequestEvent), 'kernel.request')in HttpKernel.php line 122
at HttpKernel->handleRaw(object(Request), 1)in HttpKernel.php line 68
at HttpKernel->handle(object(Request), 1, true)in Kernel.php line 201
at Kernel->handle(object(Request))in index.php line 75

I don't know what to do, I tried to add apcu.dll in my PHP in WAMP but that doesn't work.

Do you know what can I do ?

Thanks.

**Comment by denisvmedia** [comment]
You can try this tutorial to install APCu on WAMP: https://stackoverflow.com/questions/24448261/how-to-install-apcu-in-windows/42213575 .

P.S. I will close this issue because it's not something PrometheusMetricBundle specific.

**Comment by ValentinClementFr** [comment]
Thanks for your answer, after restart it worked.
