### ISSUE TITLE
Avoid service disruption in case metrics failed to be collected

### ISSUE THREAD

**Issue by pedro-stanaka** [artprima/prometheus-metrics-bundle#29]
Hello, I started using the library this week and I noticed that whenever something goes wrong when trying to capture the metrics the whole application "goes down" and requests are not served anymore. I was wondering if there is a way to isolate the subscribers so even if they throw exceptions the requests are still being served and not interrupted by exceptions in the metric themselves.

For example, suppose I use Redis as my storage for metrics and suddenly my redis cluster is down.

If this requires a new feature, please tell me the rough idea for it and I could submit PR.

**Comment by denisvmedia** [comment]
Hm. I think we need more details here. Please have a look how the metrics are being gathered: https://github.com/artprima/prometheus-metrics-bundle/blob/master/EventListener/RequestCounterListener.php

Each of 3 event handlers have there "catch-all" blocks. This may have happened only if you had an `Error` and not an `Exception`. Can you confirm that? Because if it happens, we should catch `Throwable` instead of `Exception`.

**Comment by pedro-stanaka** [comment]
I found my problem, after taking a look at the full stack trace of the exception. The problem was on the constructor of 
 `CollectorRegistry`.

```php
    public function __construct(Adapter $storageAdapter, bool $registerDefaultMetrics = true)
    {
        $this->storageAdapter = $storageAdapter;
        if ($registerDefaultMetrics) {
            $this->registerDefaultMetrics();
        }
    }
```

When booting up the kernel it would try to register this default metric of PHP version and would throw exception.

I solved it by overwriting the service definition of this class on my yaml configuration:

```yaml
    prometheus_metrics_bundle.collector_registry:
        class: Prometheus\CollectorRegistry
        arguments:
            - '@prometheus_metrics_bundle.adapter'
            - false
```

The exception I was getting before was: `Prometheus\\Exception\\StorageException` from `Prometheus\\Storage\\Redis` class (line 130).

Closing the issue out. Thanks for the quick answer.
