### ISSUE TITLE
re: do NOT add a call to init() as it will be done automatically by the relevant compiler pass

### ISSUE THREAD

**Issue by estahn** [artprima/prometheus-metrics-bundle#3]
``` 127.0.0.1:52093 [500]: /metrics - Class App\Metrics\JobMetrics contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Artprima\PrometheusMetricsBundle\Metrics\MetricsGeneratorInterface::init) in .../src/Metrics/MyMetrics.php on line 10```

**Comment by denisvmedia** [comment]
I think, the error message is pretty clear: you didn't declare the `init` function. You shouldn't call it manually, but you must have it :)

**Comment by estahn** [comment]
I had `init` declared and got another error. But all good, I will check it again later if I need to.
