### ISSUE TITLE
Add command to clear metrics

### ISSUE THREAD

**Issue by slappyslap** [artprima/prometheus-metrics-bundle#33]
All is in the title, you can add a command to clear metrics (for exemple after some performance testing)

**Comment by wuestkamp** [comment]
+1

**Comment by denisvmedia** [comment]
I agree that we need it. Unfortunately, I don't have enough time at the moment to provide us with the quality solution. And I don't know when I will have. So, if there is any volunteer to do that, the PR would be more than appreciated.

**Comment by denisvmedia** [comment]
So, I checked it. It actually is already possible, see this test code:

```php
        /** @var Adapter $adapter */
        $adapter = self::$container->get('prometheus_metrics_bundle.adapter');

        // [ .... skipped .... ]

        // wipe storage
        $adapter->wipeStorage();
```

So, you can inject `@prometheus_metrics_bundle.adapter` service to your code and call its `wipeStorage` method when you need.
