### ISSUE TITLE
support console events

### ISSUE THREAD

**Issue by ctrl-f5** [artprima/prometheus-metrics-bundle#44]
currently there are only collectors for kernel.terminate. this however does not work for console commands, since that dispatches the `ConsoleTerminateEvent`

this prevents us from providing metrics for things like Symfony/Messenger workers: number of messages processed/failed etc.

**Comment by denisvmedia** [comment]
Thank you for your PR. It makes sense. Can you please change the destination branch to `develop`?

**Comment by ctrl-f5** [comment]
sure thing, PR to develop!

**Comment by denisvmedia** [comment]
Merged. Will be released soon. Thank you for your efforts.
