### ISSUE TITLE
Use cases or examples

### ISSUE THREAD

**Issue by chiqui3d** [artprima/prometheus-metrics-bundle#49]
First, apologies for opening an issue. But I'm a bit lost. I'm currently using Grafana with Prometheus because I'm using Cadvisor to view Docker metrics, so now I'm looking for a way to get a graph on time by viewing the duration of each request in my Symfony application. So I found your great Bundle, but I'm not able to show something simple that works for me. With the number of requests I haven't had any problems, what I am not able to do is to show a graph about the time of the duration of each request and with a tooltip of the route, but as far as I can see the histograms are not good for that, right?
Don't you have some examples to get the most out of it?

So far I've managed to do this in Grafana.

![Screenshot_5](https://user-images.githubusercontent.com/2461400/118378904-15024b00-b5d7-11eb-9c36-b42b9113d102.jpg)

But this does not filter by prometheus date range. So I've managed to get this to filter by dates.

![avg-prometheus-with-range-time](https://user-images.githubusercontent.com/2461400/118376518-b1712100-b5c8-11eb-9c13-76630b7df26f.png)

Although this one I really don't know if it is well done

Finally I would like to get as I said before a graph over time, I do not know if this is possible?

Sorry again and I hope you can help me. Thanks

**Comment by denisvmedia** [comment]
Sorry, but you should reach out to the [Grafana community](https://community.grafana.com/). This bundle is just a way to expose the metrics. Moreover, it is just a Symfony wrapper around [this library](https://github.com/promphp/prometheus_client_php).

**Comment by chiqui3d** [comment]
Don't you use prometheus to create the graphics?

**Comment by denisvmedia** [comment]
Regardless of how I personally use the repo this repository is not the right place to ask these questions.
