### ISSUE TITLE
custom metric for which any of interfaces not suite

### ISSUE THREAD

**Issue by bogdandubyk** [artprima/prometheus-metrics-bundle#52]
I need to create messenger-related metrics, to count the number of messages received/sent and the amount of failed messages. But the documentation says that it's not a good idea to use `MetricsCollectorInterface`, but instead, I need to implement one of the provided interfaces. But looks like no one of them suits my needs.

What should I do in such a case? Should I implement `MetricsCollectorInterface` or is there another way to do so???

**Comment by denisvmedia** [comment]
In one of my applications I do have a similar case. In this situation, yes, you can directly implement `MetricsCollectorInterface`. This is an example how it can look like:

```php
<?php

declare(strict_types=1);

namespace App\Metrics;

use Artprima\PrometheusMetricsBundle\Metrics\MetricsCollectorInitTrait;
use Artprima\PrometheusMetricsBundle\Metrics\MetricsCollectorInterface;

final class AppMetricsCollector implements MetricsCollectorInterface
{
    use MetricsCollectorInitTrait;

    public function incMyMetric(string $labelValue): void
    {
        $counter = $this->collectionRegistry->getOrRegisterCounter(
            $this->namespace,
            'my_custom_metric',
            'my custom metric description',
            ['label']
        );
        $counter->inc([$labelValue]);
    }
```

And then in your app you can inject `AppMetricsCollector` and manually call its `incMyMetric` method.

**Comment by bogdandubyk** [comment]
okay, thank you, I was a bit confused because the documentation says it's not good to directly implement `MetricsCollectorInterface`... that why I asked.

**Comment by denisvmedia** [comment]
I will clarify that. Thanks for your feedback :)

**Comment by FractalizeR** [comment]
> I will clarify that in the docs. Thanks for your feedback :)

Have you? :) Because I have the same question. I need to send business metrics from application (say, order count) and it looks like I can inject `CollectorRegistry` into my business service to do that.

**Comment by denisvmedia** [comment]
Doesn't my example above work for you?
