### ISSUE TITLE
Can't connect to Redis server

### ISSUE THREAD

**Issue by des1roer** [artprima/prometheus-metrics-bundle#53]
![image](https://user-images.githubusercontent.com/10970793/134340444-60957412-a008-4a73-bb3f-999ef51d6df9.png)

при неправильном коннекте к редис все падает. нужно изолировать коннект к инфраструктуре из auto wiring

**Comment by denisvmedia** [comment]
If you think, there is something we can improve in the bundle, please feel free to provide a PR.
