### ISSUE TITLE
disable default metrics (php_info)

### ISSUE THREAD

**Issue by yassinekassi** [artprima/prometheus-metrics-bundle#58]
Hello, please, how can I turn off default metrics? I tried to set the value "true" to the option "disable_default_metrics" in the config file but it only disables the metrics exposed by the bundle and it does not disable the metrics exposed by the promphp / prometheus_client_php library This means that I still have the "php_info" metric among the exposed metrics

**Comment by denisvmedia** [comment]
You are right. We don't have an option to hide `php_info`. Would you be willing to provide a PR for this feature?

**Comment by yassinekassi** [comment]
unfortunately I need this option right away, could you tell me when this option will be available

**Comment by denisvmedia** [comment]
I don't have this option in my plans.

**Comment by yassinekassi** [comment]
could you please tell me if there is a method on symfony which allows to force the disactivaton of metrics by default

**Comment by yassinekassi** [comment]
for example by the explicit service declaration prometheus / collectorRegisery

**Comment by denisvmedia** [comment]
I will close this issue for now, as I don't have this feature in my plans. Feel free to create a PR, if you need it.
