### ISSUE TITLE
Adding endpoint to wipe date from storage

### ISSUE THREAD

**Issue by Johnmeurt** [artprima/prometheus-metrics-bundle#59]
The lib `prometheus_client_php ` provides the `Adapter::wipeStorage()` method to remove all data from the storage. This suggest to have access to the adapter instance.
The prometheus client does not add TTL on the redis data and the only way to control the volume is to call the wipe method.

Does it make sense to provide an endpoint (controller or cli command) to remove the data ?

**Comment by denisvmedia** [comment]
Well, I'm not sure it should be a part of the bundle. But it's easily achievable via the adapter itself. See #33.
There is also an integration test implemented in #48.

Probably this should cover your case.

P.S. Among my concerns why it was not made as a part of the bundle API were security concerns (http endpoint) and compatibility issues (APCu for example might not be available for cli apps).

**Comment by Johnmeurt** [comment]
I am agree about the security issues. I did not find this issue #33 and I thought it was not possible to get the adapter because it is declared private.
Thank you for your reply.

**Comment by denisvmedia** [comment]
Note, you cannot get it from container as it's done in the tests, but instead you should inject it as `@prometheus_metrics_bundle.adapter`.
