### ISSUE TITLE
Config : Redis Database

### ISSUE THREAD

**Issue by skhattane** [artprima/prometheus-metrics-bundle#61]
Hey,

Thanks for this great bundle. Any chance to specify which database to use for Redis storage? Actually I only see 

- host
- port
- timeout
- read_timeout
- persistent_connections
- password

**Comment by denisvmedia** [comment]
It's as simple as using `database: 1`.

**Comment by skhattane** [comment]
Thanks @denis, It could be beneficial to update the README to mention that.

**Comment by skhattane** [comment]
Why not specify it in the redis config in the README?
<img width="587" alt="image" src="https://user-images.githubusercontent.com/3841263/161173356-83b02b18-3d39-4706-ba31-ac83e61e26f2.png">

**Comment by denisvmedia** [comment]
There is no reason for that, it was just added later. You can provide a PR with the update.
