### ISSUE TITLE
Support for APCng adapter

### ISSUE THREAD

**Issue by mhavelant** [artprima/prometheus-metrics-bundle#62]
Hi!

The prom client had a v2.4.0 release, which added a new APC adapter called APCng. It would be great if this bundle could support it.

See: [prometheus_client_php v2.4.0 Release](https://github.com/PromPHP/prometheus_client_php/releases/tag/v2.4.0)

**Comment by denisvmedia** [comment]
Done in #71 (thanks to @Johnmeurt)
