### ISSUE TITLE
Support autowiring for Prometheus\CollectorRegistry

### ISSUE THREAD

**Issue by Johnmeurt** [artprima/prometheus-metrics-bundle#72]
Hello,

as the class `Prometheus\CollectorRegistry` is the interface of the library I wonder if it should be autowired.
Is there a reason to not be autowired ?
Is it relevant to add an FQCN alias on `prometheus_metrics_bundle.collector_registry` to avoid declaration in the `services.yaml` file ?

Regards

**Comment by denisvmedia** [comment]
From what I can see `Prometheus\CollectorRegistry` is actually an implementation of `Prometheus\RegistryInterface`. Anyway what benefits do you think it will bring to the bundle? Or let me ask in a different way: what obstacles do you see in the current state of the bundle?

**Comment by Johnmeurt** [comment]
I may miss something but far from what I know the only way to inject the instance of `Prometheus\RegistryInterface` is to declare your service with the parameter `prometheus_metrics_bundle.collector_registry` in the `services.yaml` file.
If the bundle declare an alias on `Prometheus\RegistryInterface`  you will not have to declare your service if autowire is enable.

**Comment by denisvmedia** [comment]
Ok, I got your point. I'm still not sure why we would need another registry implementation, but if you think it can be useful, you can provide a PR and I will merge it.

**Comment by Johnmeurt** [comment]
Not another registry, just makes more user friendly the declaration of service that needs the registry.
Sorry if I am not clear. I try an exemple:

I have got this class:
```php
use Prometheus\CollectorRegistry;

class ClassThatWillCreateMetrics
{
    public function __construct(CollectorRegistry $registry)
    {
    }
}
```
Autowire does not work in that example. I have to declare the class in `services.yaml `
```yaml
services:
    ClassThatWillCreateMetrics:
        arguments:
            - '@prometheus_metrics_bundle.collector_registry'
```
To avoid this declaration the bundle could add alias of  `Prometheus\CollectorRegistry` on `prometheus_metrics_bundle.collector_registry`
It could also add `Prometheus\RegistryInterface` on `prometheus_metrics_bundle.collector_registry`

But I feel like I am the only one to have this issue. This is why I think I miss something.

Anyway it could wait for another version.
You can close this if you see no use case.

**Comment by denisvmedia** [comment]
Update: the docs say that `MetricsCollectorInterface` should not be implemented directly, but I most likely made a mistake stating it.

**Comment by Johnmeurt** [comment]
Ok I see. My use case is in the messenger bus (I add a messager middleware) which is not under the scope of the console and request events.
Thanks for the response. I am closing the ticket.
