### ISSUE TITLE
Clear metrics uses incorrect prefix for APCu

### ISSUE THREAD

**Issue by pluk77** [artprima/prometheus-metrics-bundle#79]
Symfony 5.4
Storage: APCu

I have set a prefix in the prometheus_metrics.yaml file, which works. I am collecting custom as well as standard metrics, which all reflect in metrics/prometheus as expected with the correct prefix / namespace.

however, when I try to clear the metrics via the CLI, nothing happens.

Dumping the prefix shows that the standard 'prom' prefix is used, not the one I configured. I suspect this is why nothing is removed?

Am I doing something wrong or missing a config step?

**Comment by denisvmedia** [comment]
You might probably have different settings for different environments.

**Comment by pluk77** [comment]
I will close this issue, as the problem is not the key or prefix, it is APCu itself. 

For some reason i can not get the data to clear, no matter what I try.
