### ISSUE TITLE
User Deprecated: Method "Symfony\Component\HttpKernel\Bundle\Bundle::build()" might add "void"

### ISSUE THREAD

**Issue by nforced** [artprima/prometheus-metrics-bundle#88]
I see this deprecation in Symfony 6.3 with version 1.17.0

`deprecation.INFO: User Deprecated: Method "Symfony\Component\HttpKernel\Bundle\Bundle::build()" might add "void" as a native return type declaration in the future. Do the same in child class "Artprima\PrometheusMetricsBundle\ArtprimaPrometheusMetricsBundle" now to avoid errors or add an explicit @return annotation to suppress this message. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Method \"Symfony\\Component\\HttpKernel\\Bundle\\Bundle::build()\" might add \"void\" as a native return type declaration in the future. Do the same in child class \"Artprima\\PrometheusMetricsBundle\\ArtprimaPrometheusMetricsBundle\" now to avoid errors or add an explicit @return annotation to suppress this message. at /var/www/html/vendor/symfony/error-handler/DebugClassLoader.php:337)"} []`

**Comment by denisvmedia** [comment]
Would you mind providing a PR for that?
