### ISSUE TITLE
Question: Can I push metrics to Pushgateway using this library?

### ISSUE THREAD

**Issue by smamykin** [artprima/prometheus-metrics-bundle#89]
Hello. 

I have batch jobs where I would like to collect metrics too. Having read recommendations in [the doc](https://prometheus.io/docs/practices/pushing/) I want to push some metrics to prometheus. 

As I can see, there is no such feature in this library. Am I wrong? 

Could you advise some other libraries that have the feature, please?

I would be appreciated for any answer. Thank you.

**Comment by Johnmeurt** [comment]
Hello,

this bundle only provides the features from the lib `promphp/prometheus_client_php`.  You should check there if the push gateway is available. I am not sure but I think they moved the pushgateway part of this lib in an other one. See their README for more information.

**Comment by denisvmedia** [comment]
Thank you @Johnmeurt, it's true.
