### ISSUE TITLE
404 Not Found - There was an error returned querying the Prometheus API.

### ISSUE THREAD

**Issue by LLayton** [artprima/prometheus-metrics-bundle#90]
Hello, 
I tried to make à dashbord to get metric about my symfony app.
I would like to know if there is à way to connect my_url/metrics/prometheus to a docker container with grafana.
Do i need to create a connector ? 
Do i need to set up an exporter ? 
Thank you in advance.

![Prometheus - Data sources - Administration - Grafana - Opera](https://github.com/artprima/prometheus-metrics-bundle/assets/72615434/bdbf58b5-e6fe-4fdf-aff9-67803aed937a)

**Comment by Johnmeurt** [comment]
Hi,

this bundle only provides access to the lib `promphp/prometheus_client_php`. The way it works is pretty much like this:

your app send metrics to a storage defined by your config (as apcu, redis...). The route `https://myapi.com/metrics/prometheus` expose those metrics  in a exposition format (see https://github.com/prometheus/docs/blob/main/content/docs/instrumenting/exposition_formats.md).
```
# HELP http_requests_total The total number of HTTP requests.
# TYPE http_requests_total counter
http_requests_total{method="post",code="200"} 1027 1395066363000
http_requests_total{method="post",code="400"}    3 1395066363000
```
That's all the lib / bundle do.

The next step is to configure your prometheus to scrape your metrics. Its job is to import your metrics in its storage.
In the prometheus config:
```
# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name:       'node'
    metrics_path: /metrics/prometheus
    static_configs:
      - targets: ['localhost:8080']
```
The configure your grafana to search metrics from prometheus (Your screen seems to be that step).

See https://prometheus.io/docs/prometheus/latest/configuration/configuration/ for more details.

**Comment by denisvmedia** [comment]
Thank you @Johnmeurt, this is an exhaustive answer. I'll close the issue.
