### ISSUE TITLE
No values returned

### ISSUE THREAD

**Issue by tricasoft** [artprima/prometheus-metrics-bundle#99]
I installed the library with Synfony 6, but the response is an empty page.
What could be wrong?

This is my setup:
artprima_prometheus_metrics:
    namespace: appName
    storage: in_memory

    ignored_routes:
        - prometheus_bundle_prometheus
        - _wdt

    # used to disable default application metrics
    disable_default_metrics: false

    # Recommended to disable default metrics from promphp/prometheus_client_php
    # see https://github.com/PromPHP/prometheus_client_php/issues/62
    disable_default_promphp_metrics: true

    # used to enable console metrics
    enable_console_metrics: true

**Comment by denisvmedia** [comment]
`storage: in_memory` - this is not meant to be used other than in tests. You should use `apcu`, `apcng` or `redis` instead.

**Comment by tricasoft** [comment]
You're right, but please update the documentation about this, I spent a lot of time looking for the problem...
